.PHONY: clean All

All:
	@echo "----------Building project:[ Tower_of_Hanoi - Debug ]----------"
	@cd "Tower_of_Hanoi" && "$(MAKE)" -f  "Tower_of_Hanoi.mk"
clean:
	@echo "----------Cleaning project:[ Tower_of_Hanoi - Debug ]----------"
	@cd "Tower_of_Hanoi" && "$(MAKE)" -f  "Tower_of_Hanoi.mk" clean
